# Generated by Django 4.1.3 on 2022-12-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_data_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AddField(
            model_name='lesson',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
